FROM openjdk:19-jdk-alpine

WORKDIR /app

COPY ./build/libs/app.jar /app/app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]

FROM openjdk:19-jdk-alpine

WORKDIR /app

COPY ./build/libs/app.jar /app/app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]